CREATE DATABASE ass3;

use ass3;

CREATE TABLE DEPARTMENT(
  DEPTCODE VARCHAR(10) PRIMARY KEY,
  NAME VARCHAR(15) NOT NULL
);

CREATE TABLE EMPLOYEE(
  EMPCODE CHAR(5) PRIMARY KEY,
  NAME VARCHAR(25) NOT NULL ,
  ADDRESS VARCHAR(50) NOT NULL,
  CITY VARCHAR(20) NOT NULL,
  BASIC INTEGER NOT NULL ,
  GRADE CHAR(1) NOT NULL ,
  JN_DATE DATE DEFAULT(CURRENT_DATE),
  DEPTCODE VARCHAR(10) NOT NULL,
  FOREIGN KEY(DEPTCODE) REFERENCES DEPARTMENT(DEPTCODE) ON DELETE RESTRICT,
  CONSTRAINT NAME_UPPERCASE_CONSTRAINT CHECK(BINARY NAME = BINARY UPPER(NAME)),
  CONSTRAINT BASIC_RANGE_CONSTRAINT CHECK(BASIC>=5000 AND BASIC<=9000),
  CONSTRAINT GRADE_CONSTRAINT CHECK(GRADE IN ('A','B','C'))
);

CREATE TABLE LEAVE_REGISTER(
  EMPCODE CHAR(5) NOT NULL,
  LEAVE_TYPE CHAR(5) NOT NULL,
  FROM_DATE DATE NOT NULL,
  TO_DATE DATE NOT NULL,
  PRIMARY KEY(FROM_DATE,EMPCODE),
  FOREIGN KEY(EMPCODE) REFERENCES EMPLOYEE(EMPCODE) ON DELETE CASCADE,
  CONSTRAINT TYPE_CONSTRAINT CHECK(LEAVE_TYPE IN ('CL', 'EL', 'ML'))
);

