USE ass3;

INSERT INTO DEPARTMENT VALUES('CSE', 'COPUTER SCIENCE');
INSERT INTO DEPARTMENT VALUES('PROD', 'PRODUCTION');
INSERT INTO DEPARTMENT VALUES('FIN', 'FINANCE');
INSERT INTO DEPARTMENT VALUES('FOOD', 'FOOD TECHNOLOGY');

SELECT * FROM DEPARTMENT;

INSERT INTO EMPLOYEE VALUES('EMP1', 'RAHUL MODAK', 'KOLKATA', 'KOLKATA', 6000, 'A', '2022-03-04', 'CSE');
INSERT INTO EMPLOYEE VALUES('EMP2', 'RAM', 'KOLKATA', 'KOLKATA', 8000, 'A', '2022-01-04', 'PROD');
INSERT INTO EMPLOYEE VALUES('EMP3', 'SHYAM', 'KOLKATA', 'KOLKATA', 7000, 'A', '2022-07-04', 'CSE');
INSERT INTO EMPLOYEE VALUES('EMP4', 'NAYAN', 'KOLKATA', 'KOLKATA', 7000, 'A', '2021-07-04', 'CSE');
INSERT INTO EMPLOYEE VALUES('EMP5', 'SAYAN', 'KOLKATA', 'KOLKATA', 7000, 'A', '2021-07-04', 'PROD');

INSERT INTO LEAVE_REGISTER VALUES('EMP1', 'BL', '2022-03-04', '2022-04-04');

CREATE TABLE NEW_EMPLOYEE AS
SELECT EMPLOYEE.EMPCODE, EMPLOYEE.NAME, EMPLOYEE.BASIC, DEPARTMENT.NAME AS DEPARTMENT_NAME
FROM EMPLOYEE
INNER JOIN DEPARTMENT ON DEPARTMENT.DEPTCODE = EMPLOYEE.DEPTCODE
WHERE EMPLOYEE.BASIC = 7000 AND EMPLOYEE.DEPTCODE = 'CSE';

INSERT INTO NEW_EMPLOYEE (
	SELECT EMPLOYEE.EMPCODE, EMPLOYEE.NAME, EMPLOYEE.BASIC, DEPARTMENT.NAME AS DEPARTMENT_NAME FROM EMPLOYEE
    INNER JOIN DEPARTMENT ON DEPARTMENT.DEPTCODE = EMPLOYEE.DEPTCODE
    WHERE EMPLOYEE.BASIC >= 7000
);

-- Alter the table to add a net pay column
ALTER TABLE NEW_EMPLOYEE ADD NET_PAY INT;
DESCRIBE NEW_EMPLOYEE;
UPDATE NEW_EMPLOYEE SET NET_PAY = 1.5*BASIC;
SELECT DISTINCT EMPCODE, NAME, DEPARTMENT_NAME, BASIC, NET_PAY FROM NEW_EMPLOYEE;

-- Try to remove the net net pay column.
ALTER TABLE NEW_EMPLOYEE DROP COLUMN NET_PAY;